### ISSUE TITLE
Change license to an OSI-approved non-copyleft license

### ISSUE THREAD

**Issue by piyueh** [jazzband/imaplib2#18]
There's no actual license file in this repository. However, according to the original project page on [Sourceforge](https://sourceforge.net/projects/imaplib2/), the license seems to be [CNRI Python License](https://opensource.org/licenses/CNRI-Python). I'm not a lawyer or something, but this license does not look proper to me. For example, the terms seem to cover the Python interpreter, not the Python package itself? And the copyright owner of the package seems to be the Corporation for National Research Initiatives?

So I'm proposing changing the license to any modern OSI-approved non-copyleft license, like MIT, BSD 3, etc. To change the license, it requires the code contributors of this repository to give consents.

As @jezdez stated in [#13](https://github.com/jazzband/imaplib2/issues/13#issuecomment-803160097), the process of gathering consents should be open. Hence, let's use this issue to track the consents from the contributors:

* [x] Alexander Kavanaugh (@kavdev)
* [x] Benjamin E. Coe (@bcoe)
* [x] David Keijser (@keis)
* [x] Ilias Tsitsimpis (@iliastsi)
* [x] John Molyneux (@johnmolyneux)
* [x] Julien Cristau (@jcristau)
* ~[ ] Mark Hahnenberg (@mhahnenberg)~
* [x] Piers Lauder (consent through email)
* [x] Rob Adams (@rfadams)
* [x] Rodolfo García Peñas (@thekix)
* [x] Thomas Grainger (@graingert)

If no one has a strong objection, let's change to the ~BSD 3-Clause~ MIT license. Please leave a message in this issue to give your consent to change to ~BSD 3-Clause~ MIT. Thank you!

I'm not familiar with other non-copyleft licenses, so if anyone has other suggestions, we can also discuss the alternatives in this issue. I'm fine with either MIT or BSD 3-Clause. If anyone has a strong favor over MIT or BSD 3-Clause, please indicate it.

**Comment by kavdev** [comment]
Works for me. I'd lean towards the MIT license if that's an option.

**Comment by johnmolyneux** [comment]
License change fine by me, I have no preference between BSD 3-Clause / MIT license.

**Comment by thekix** [comment]
No problem for me.

**Comment by keis** [comment]
According to the README this is based on the original imaplib so you may need to get a sign-off from more people (But I'm not a lawyer and copyright is a scam)

I'm ok changing the license to any OSI approved license.

**Comment by piyueh** [comment]
> According to the README this is based on the original imaplib so you may need to get a sign-off from more people (But I'm not a lawyer and copyright is a scam)
> 
> I'm ok changing the license to any OSI approved license.

The original `imaplib.py` (now a Python built-in module) was also created by Piers Lauder. I already got Piers Lauder's consent, through email exchanges, to change the license. Let's hope this is enough...

**Comment by iliastsi** [comment]
I'm ok changing the license to MIT.

**Comment by rfadams** [comment]
+1. I’m also ok with changing the license. ``

**Comment by bcoe** [comment]
I am supportive of changing the license 👍

**Comment by bcoe** [comment]
Keeping in mind I just originally published this library, Piers Lauder had originally put the work up on Source Forge I believe. Thank you for the work Piers.

**Comment by graingert** [comment]
the changes from mhahnenberg are no longer present, (eg 2to3 isn't used anymore)

https://github.com/jazzband/imaplib2/commits?author=mhahnenberg

**Comment by graingert** [comment]
I couldn't find any commits by jcristau https://github.com/jazzband/imaplib2/commits?author=jcristau

**Comment by piyueh** [comment]
I think jcristau's commits is a7ce7da1d573849ac2e1d740d8f3238e0ad8d88c, merged from PR #6

**Comment by piyueh** [comment]
@graingert I don't see your consent, but the checkbox is checked. I guess I made a mistake. I'm unchecking it now until you give a written consent here.

**Comment by graingert** [comment]
Oh I just ticked the box

**Comment by piyueh** [comment]
Oh, that's cool! I didn't know non-authors of a comment can check the box. :P

**Comment by piyueh** [comment]
Pinging @jcristau

**Comment by jcristau** [comment]
Sorry, I don't tend to pay attention to github notifications.  Fine with me.

**Comment by graingert** [comment]
@piyueh that's it everyone's done!

**Comment by piyueh** [comment]
It's awesome!
