### ISSUE TITLE
swap coveralls for codecov

### ISSUE THREAD

**Issue by graingert** [jazzband/imaplib2#24]
Hey all, I noticed this is using Coveralls, could you please use Codecov instead to reduce the number of services?

_Originally posted by @jezdez in https://github.com/jazzband/imaplib2/issues/23#issuecomment-858416987_

**Comment by jezdez** [comment]
Apologies for not noticing earlier that the TODO list in #13 was still the old one that had Coveralls listed. After the issues with Travis-CI and Coveralls I decided to reduce the number of services Jazzband relies on to reduce the dependencies.

Ironically that was again *before* the [Codecov security incident](https://github.com/orgs/jazzband/teams/members/discussions/6) and I'm still researching a better option for all Jazzband projects eventually. In the meantime, I appreciate your help in moving to Codecov.
